---
title: "Annex: Zambia CSIP"
author: "ADD Authors"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  word_document:
    reference_docx: ../Support/word_styles_01.docx
bibliography: ../Bib/CSIP_ZMB.bib
---

```{r setup, include=FALSE}
library(pacman)
p_load(rprojroot)
root <- find_root(is_rstudio_project)

tempPath <- "C:/Users/vandijkm/Github/Global-to-local-GLOBIOM/Code/ZMB"

p_load(knitr)
knitr::opts_chunk$set(
  fig.width=12, fig.height=8,
  dpi = 300,
  echo=FALSE, warning=FALSE, message=FALSE,
  fig.path = file.path(root,"Fig_tab_map/out-"),
  dev = "CairoPNG",
  dev.args = list(CairoPNG = list(bg = "transparent"))
  )

p_load(pander)
panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)

#source(file.path(tempPath, "Scripts/Fig.R"))
#source(file.path(root, "Scripts/Tab.R"))
source(file.path(root, "Scripts/Map.R"))
```


# Land use maps for X crops


```{r Fig_pop_gdp}
#fig_ssp_pop
#gig_ssp_gdp
fig_adm1
```


